# Generated by Django 4.1.3 on 2023-03-02 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_play_quizplay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='availible',
        ),
    ]
