# Generated by Django 4.1.3 on 2023-03-02 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_remove_questions_availible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ['id'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='quizzes',
            options={'ordering': ['id'], 'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.RemoveField(
            model_name='quizplay',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='quizplay',
            name='average',
        ),
        migrations.RemoveField(
            model_name='quizplay',
            name='percentage',
        ),
    ]
