# Generated by Django 4.1.3 on 2023-03-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_questions_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizplay',
            name='attempt',
            field=models.IntegerField(default=1),
        ),
    ]
