# Generated by Django 4.1.3 on 2023-03-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_quizplay_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizplay',
            name='satus',
            field=models.CharField(default='Failed', max_length=12),
        ),
    ]
