# Generated by Django 4.1.3 on 2023-03-03 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_quizplay_satus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizplay',
            old_name='satus',
            new_name='status',
        ),
    ]
